import type { Metadata } from 'next';
import { Anton, Lora, Roboto } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ClientLenisProvider } from '@/components/Lenis/ClientLenisProvider';
import Footer from '@/components/Footer/Footer';

const anton = Anton({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-anton',
});

const lora = Lora({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-lora',
});

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'GrandFit&Beauty, Dubrovnik',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${anton.variable} ${lora.variable} ${roboto.variable} font-sans antialiased bg-zinc-50 dark:bg-black text-black dark:text-white`}>
				<Navbar />
				<ClientLenisProvider>{children}</ClientLenisProvider>
				<Footer />
			</body>
		</html>
	);
}
